#!/usr/bin/env python3
"""
Erzeugt src/EasyService/Resources/Strings.g.cs aus Strings.resx.

    python tools/generate-strings.py

Die .resx-Dateien sind die Quelle der Wahrheit - sie sind das Format, mit dem
Uebersetzungsdienste (Crowdin, Weblate, POEditor) umgehen koennen. Dieses Skript
ersetzt lediglich den ResXFileCodeGenerator von Visual Studio, damit der Build
auch ohne VS reproduzierbar ist.

Schluessel mit Platzhaltern ({0}, {1}, ...) werden zu Methoden mit passender
Parameterzahl, alle anderen zu Eigenschaften. Ein vertippter Schluessel ist damit
ein Compilerfehler statt einer Ueberraschung zur Laufzeit.
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESX = ROOT / "src" / "EasyService" / "Resources" / "Strings.resx"
OUT = ROOT / "src" / "EasyService" / "Resources" / "Strings.g.cs"

HEADER = """// <auto-generated>
//     Erzeugt von tools/generate-strings.py aus Strings.resx.
//     Nicht von Hand bearbeiten - Aenderungen gehen beim naechsten Lauf verloren.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace EasyService.Resources;

/// <summary>
/// Alle Texte der Oberflaeche. Englisch ist die Neutralsprache, Deutsch liegt als
/// Uebersetzung daneben; welche greift, entscheidet <see cref="Localization"/>.
/// </summary>
internal static class S
{
    private static readonly ResourceManager Manager =
        new("EasyService.Resources.Strings", typeof(S).Assembly);

    private static string Get(string key) =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    private static string Fmt(string key, params object?[] args) =>
        string.Format(CultureInfo.CurrentUICulture, Get(key), args);
"""


def read_entries(path: Path) -> list[tuple[str, str, str]]:
    tree = ET.parse(path)
    entries = []
    for node in tree.getroot().findall("data"):
        name = node.get("name")
        if name is None:
            continue
        value = node.findtext("value") or ""
        comment = node.findtext("comment") or ""
        entries.append((name, value, comment))
    return sorted(entries, key=lambda e: e[0])


def placeholder_count(value: str) -> int:
    indexes = {int(m) for m in re.findall(r"\{(\d+)[^}]*\}", value)}
    return max(indexes) + 1 if indexes else 0


def escape_doc(text: str) -> str:
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return " ".join(text.split())


def main() -> None:
    if not RESX.exists():
        sys.exit(f"Nicht gefunden: {RESX}")

    entries = read_entries(RESX)
    lines = [HEADER]

    for name, value, comment in entries:
        doc = escape_doc(value)
        if len(doc) > 160:
            doc = doc[:157] + "..."
        lines.append(f"\n    /// <summary>{doc}</summary>")
        if comment:
            lines.append(f"    /// <remarks>{escape_doc(comment)}</remarks>")

        count = placeholder_count(value)
        if count == 0:
            lines.append(f'    public static string {name} => Get("{name}");')
        else:
            params = ", ".join(f"object? p{i}" for i in range(count))
            args = ", ".join(f"p{i}" for i in range(count))
            lines.append(f'    public static string {name}({params}) => Fmt("{name}", {args});')

    lines.append("}\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}  ({len(entries)} Schluessel)")


if __name__ == "__main__":
    main()
