// <auto-generated>
//     Erzeugt von tools/generate-strings.py aus Strings.resx.
//     Nicht von Hand bearbeiten - Aenderungen gehen beim naechsten Lauf verloren.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace EasyService.Resources;

/// <summary>
/// Alle Texte der Oberflaeche. Englisch ist die Neutralsprache, Deutsch liegt als
/// Uebersetzung daneben; welche greift, entscheidet <see cref="Localization"/>.
/// </summary>
internal static class S
{
    private static readonly ResourceManager Manager =
        new("EasyService.Resources.Strings", typeof(S).Assembly);

    private static string Get(string key) =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    private static string Fmt(string key, params object?[] args) =>
        string.Format(CultureInfo.CurrentUICulture, Get(key), args);


    /// <summary>An account name is required to log on as an account.</summary>
    public static string Cfg_Err_AccountRequired => Get("Cfg_Err_AccountRequired");

    /// <summary>Program not found: {0}</summary>
    public static string Cfg_Err_AppNotFound(object? p0) => Fmt("Cfg_Err_AppNotFound", p0);

    /// <summary>Invalid environment variable (expected NAME=VALUE): {0}</summary>
    public static string Cfg_Err_BadEnvironment(object? p0) => Fmt("Cfg_Err_BadEnvironment", p0);

    /// <summary>Startup directory not found: {0}</summary>
    public static string Cfg_Err_DirNotFound(object? p0) => Fmt("Cfg_Err_DirNotFound", p0);

    /// <summary>"{0}" already exists but was not created with EasyService. Importing would overwrite a foreign service.</summary>
    public static string Cfg_Err_Foreign(object? p0) => Fmt("Cfg_Err_Foreign", p0);

    /// <summary>Not a host:port pair: {0}</summary>
    public static string Cfg_Err_HealthEndpoint(object? p0) => Fmt("Cfg_Err_HealthEndpoint", p0);

    /// <summary>At least one failed check is needed before a service counts as unhealthy.</summary>
    public static string Cfg_Err_HealthFailures => Get("Cfg_Err_HealthFailures");

    /// <summary>The health check interval has to be at least one second.</summary>
    public static string Cfg_Err_HealthInterval => Get("Cfg_Err_HealthInterval");

    /// <summary>The health check needs a target: a URL, host:port, a file or a command line.</summary>
    public static string Cfg_Err_HealthTarget => Get("Cfg_Err_HealthTarget");

    /// <summary>Not an http or https address: {0}</summary>
    public static string Cfg_Err_HealthUrl(object? p0) => Fmt("Cfg_Err_HealthUrl", p0);

    /// <summary>The service name must not be empty.</summary>
    public static string Cfg_Err_NameEmpty => Get("Cfg_Err_NameEmpty");

    /// <summary>The service name must not contain / or \.</summary>
    public static string Cfg_Err_NameSlash => Get("Cfg_Err_NameSlash");

    /// <summary>The service name is too long (256 characters maximum).</summary>
    public static string Cfg_Err_NameTooLong => Get("Cfg_Err_NameTooLong");

    /// <summary>The configuration logs on as "{0}". Passwords are never exported - set {1} before importing.</summary>
    public static string Cfg_Err_NeedsPassword(object? p0, object? p1) => Fmt("Cfg_Err_NeedsPassword", p0, p1);

    /// <summary>This configuration was written by a newer version of EasyService (format {0}).</summary>
    public static string Cfg_Err_NewerFormat(object? p0) => Fmt("Cfg_Err_NewerFormat", p0);

    /// <summary>No program was specified.</summary>
    public static string Cfg_Err_NoApplication => Get("Cfg_Err_NoApplication");

    /// <summary>The configuration has no service name.</summary>
    public static string Cfg_Err_NoServiceName => Get("Cfg_Err_NoServiceName");

    /// <summary>The file is not an EasyService configuration.</summary>
    public static string Cfg_Err_NotConfig => Get("Cfg_Err_NotConfig");

    /// <summary>The file is not valid JSON: {0}</summary>
    public static string Cfg_Err_NotJson(object? p0) => Fmt("Cfg_Err_NotJson", p0);

    /// <summary>Export failed</summary>
    public static string Cfg_Export_Failed => Get("Cfg_Export_Failed");

    /// <summary>Configuration written to {0}</summary>
    public static string Cfg_Exported(object? p0) => Fmt("Cfg_Exported", p0);

    /// <summary>{0} configurations written to {1}</summary>
    public static string Cfg_ExportedMany(object? p0, object? p1) => Fmt("Cfg_ExportedMany", p0, p1);

    /// <summary>EasyService configuration (*.json)|*.json|All files (*.*)|*.*</summary>
    public static string Cfg_Filter => Get("Cfg_Filter");

    /// <summary>Import failed</summary>
    public static string Cfg_Import_Failed => Get("Cfg_Import_Failed");

    /// <summary>The service "{0}" already exists. Overwrite its configuration?</summary>
    public static string Cfg_Import_Overwrite(object? p0) => Fmt("Cfg_Import_Overwrite", p0);

    /// <summary>Password for "{0}":</summary>
    public static string Cfg_Import_PasswordPrompt(object? p0) => Fmt("Cfg_Import_PasswordPrompt", p0);

    /// <summary>The service is running; the changes take effect after a restart.</summary>
    public static string Cfg_Import_Restart => Get("Cfg_Import_Restart");

    /// <summary>Import configuration</summary>
    public static string Cfg_Import_Title => Get("Cfg_Import_Title");

    /// <summary>Service "{0}" was created from the configuration.</summary>
    public static string Cfg_Imported_Created(object? p0) => Fmt("Cfg_Imported_Created", p0);

    /// <summary>Service "{0}" was updated from the configuration.</summary>
    public static string Cfg_Imported_Updated(object? p0) => Fmt("Cfg_Imported_Updated", p0);

    /// <summary>Error: {0}</summary>
    public static string Cli_Err(object? p0) => Fmt("Cli_Err", p0);

    /// <summary>"{0}" needs administrator rights. Run the command from a command prompt opened as administrator.</summary>
    public static string Cli_Err_NeedsAdmin(object? p0) => Fmt("Cli_Err_NeedsAdmin", p0);

    /// <summary>export requires &lt;name&gt; or --all.</summary>
    public static string Cli_ExportNeedsName => Get("Cli_ExportNeedsName");

    /// <summary>File not found: {0}</summary>
    public static string Cli_FileNotFound(object? p0) => Fmt("Cli_FileNotFound", p0);

    /// <summary>DISPLAY NAME</summary>
    public static string Cli_Hdr_DisplayName => Get("Cli_Hdr_DisplayName");

    /// <summary>NAME</summary>
    public static string Cli_Hdr_Name => Get("Cli_Hdr_Name");

    /// <summary>STARTUP</summary>
    public static string Cli_Hdr_Startup => Get("Cli_Hdr_Startup");

    /// <summary>STATUS</summary>
    public static string Cli_Hdr_Status => Get("Cli_Hdr_Status");

    /// <summary>UNHEALTHY - {0} ({1} ms)</summary>
    public static string Cli_Health_Failed(object? p0, object? p1) => Fmt("Cli_Health_Failed", p0, p1);

    /// <summary>No health check configured for "{0}".</summary>
    public static string Cli_Health_None(object? p0) => Fmt("Cli_Health_None", p0);

    /// <summary>healthy - {0} ({1} ms)</summary>
    public static string Cli_Health_Ok(object? p0, object? p1) => Fmt("Cli_Health_Ok", p0, p1);

    /// <summary>import requires a file.</summary>
    public static string Cli_ImportNeedsFile => Get("Cli_ImportNeedsFile");

    /// <summary>install requires &lt;name&gt; and &lt;program&gt;.</summary>
    public static string Cli_InstallNeedsArgs => Get("Cli_InstallNeedsArgs");

    /// <summary>Service "{0}" was created.</summary>
    public static string Cli_Installed(object? p0) => Fmt("Cli_Installed", p0);

    /// <summary>Logs: {0}</summary>
    public static string Cli_Logs(object? p0) => Fmt("Cli_Logs", p0);

    /// <summary>{0} services written to {1}.</summary>
    public static string Cli_MetricsWritten(object? p0, object? p1) => Fmt("Cli_MetricsWritten", p0, p1);

    /// <summary>EASYSERVICE UNKNOWN - monitoring is disabled for "{0}".</summary>
    public static string Cli_MonitoringOff(object? p0) => Fmt("Cli_MonitoringOff", p0);

    /// <summary>{0} requires &lt;name&gt;.</summary>
    public static string Cli_NeedsName(object? p0) => Fmt("Cli_NeedsName", p0);

    /// <summary>Error: service "{0}" does not exist.</summary>
    public static string Cli_NotExists(object? p0) => Fmt("Cli_NotExists", p0);

    /// <summary>No services managed by EasyService were found.</summary>
    public static string Cli_NothingToExport => Get("Cli_NothingToExport");

    /// <summary>--output requires a file name.</summary>
    public static string Cli_OutputNeedsFile => Get("Cli_OutputNeedsFile");

    /// <summary>Service "{0}" was removed.</summary>
    public static string Cli_Removed(object? p0) => Fmt("Cli_Removed", p0);

    /// <summary>Service "{0}" was restarted.</summary>
    public static string Cli_Restarted(object? p0) => Fmt("Cli_Restarted", p0);

    /// <summary>Account : {0}</summary>
    public static string Cli_St_Account(object? p0) => Fmt("Cli_St_Account", p0);

    /// <summary>Application : {0}</summary>
    public static string Cli_St_Application(object? p0) => Fmt("Cli_St_Application", p0);

    /// <summary>CPU / RAM : {0} % / {1}</summary>
    public static string Cli_St_CpuRam(object? p0, object? p1) => Fmt("Cli_St_CpuRam", p0, p1);

    /// <summary>Display name: {0}</summary>
    public static string Cli_St_DisplayName(object? p0) => Fmt("Cli_St_DisplayName", p0);

    /// <summary>Last error : {0}</summary>
    public static string Cli_St_LastError(object? p0) => Fmt("Cli_St_LastError", p0);

    /// <summary>Last exit : code {0}</summary>
    public static string Cli_St_LastExit(object? p0) => Fmt("Cli_St_LastExit", p0);

    /// <summary>on {0}</summary>
    public static string Cli_St_LastExitAt(object? p0) => Fmt("Cli_St_LastExitAt", p0);

    /// <summary>Managed : {0}</summary>
    public static string Cli_St_Managed(object? p0) => Fmt("Cli_St_Managed", p0);

    /// <summary>Name : {0}</summary>
    public static string Cli_St_Name(object? p0) => Fmt("Cli_St_Name", p0);

    /// <summary>no</summary>
    public static string Cli_St_No => Get("Cli_St_No");

    /// <summary>({0} processes)</summary>
    public static string Cli_St_Processes(object? p0) => Fmt("Cli_St_Processes", p0);

    /// <summary>Program : {0}</summary>
    public static string Cli_St_Program(object? p0) => Fmt("Cli_St_Program", p0);

    /// <summary>Restarts : {0} in the last hour, {1} in 24 h, {2} total</summary>
    public static string Cli_St_Restarts(object? p0, object? p1, object? p2) => Fmt("Cli_St_Restarts", p0, p1, p2);

    /// <summary>Startup : {0}</summary>
    public static string Cli_St_Startup(object? p0) => Fmt("Cli_St_Startup", p0);

    /// <summary>Status : {0}</summary>
    public static string Cli_St_Status(object? p0) => Fmt("Cli_St_Status", p0);

    /// <summary>stderr : {0}</summary>
    public static string Cli_St_Stderr(object? p0) => Fmt("Cli_St_Stderr", p0);

    /// <summary>stdout : {0}</summary>
    public static string Cli_St_Stdout(object? p0) => Fmt("Cli_St_Stdout", p0);

    /// <summary>Uptime : {0}</summary>
    public static string Cli_St_Uptime(object? p0) => Fmt("Cli_St_Uptime", p0);

    /// <summary>yes (EasyService)</summary>
    public static string Cli_St_Yes => Get("Cli_St_Yes");

    /// <summary>Service "{0}" was started.</summary>
    public static string Cli_Started(object? p0) => Fmt("Cli_Started", p0);

    /// <summary>Service "{0}" was stopped.</summary>
    public static string Cli_Stopped(object? p0) => Fmt("Cli_Stopped", p0);

    /// <summary>Unknown command: {0}</summary>
    public static string Cli_UnknownCommand(object? p0) => Fmt("Cli_UnknownCommand", p0);

    /// <summary>easyservice - manage Windows services through a GUI (alternative to nssm.exe) Without arguments the graphical interface starts. MANAGE easyservice list [--js...</summary>
    public static string Cli_Usage => Get("Cli_Usage");

    /// <summary>Cancel</summary>
    public static string Common_Cancel => Get("Common_Cancel");

    /// <summary>Clipboard</summary>
    public static string Common_Clipboard => Get("Common_Clipboard");

    /// <summary>Error</summary>
    public static string Common_Error => Get("Common_Error");

    /// <summary>Explorer</summary>
    public static string Common_Explorer => Get("Common_Explorer");

    /// <summary>Log files (*.log;*.txt)|*.log;*.txt|All files (*.*)|*.*</summary>
    public static string Common_FilterLog => Get("Common_FilterLog");

    /// <summary>Programs (*.exe;*.bat;*.cmd)|*.exe;*.bat;*.cmd|All files (*.*)|*.*</summary>
    public static string Common_FilterProgram => Get("Common_FilterProgram");

    /// <summary>Log file (*.log)|*.log|Text file (*.txt)|*.txt|All files (*.*)|*.*</summary>
    public static string Common_FilterSaveLog => Get("Common_FilterSaveLog");

    /// <summary>Remove</summary>
    public static string Common_Remove => Get("Common_Remove");

    /// <summary>Save</summary>
    public static string Common_Save => Get("Common_Save");

    /// <summary>Unexpected error</summary>
    public static string Common_UnexpectedError => Get("Common_UnexpectedError");

    /// <summary>?</summary>
    public static string Common_UnknownShort => Get("Common_UnknownShort");

    /// <summary>To confirm, please type the service name: {0}</summary>
    public static string Confirm_Text(object? p0) => Fmt("Confirm_Text", p0);

    /// <summary>Confirm deletion</summary>
    public static string Confirm_Title => Get("Confirm_Title");

    /// <summary>Add</summary>
    public static string Editor_Btn_Add => Get("Editor_Btn_Add");

    /// <summary>Copy to clipboard</summary>
    public static string Editor_Btn_Copy => Get("Editor_Btn_Copy");

    /// <summary>Create service</summary>
    public static string Editor_Btn_Create => Get("Editor_Btn_Create");

    /// <summary>Test now</summary>
    public static string Editor_Btn_HealthTest => Get("Editor_Btn_HealthTest");

    /// <summary>Select services...</summary>
    public static string Editor_Btn_PickServices => Get("Editor_Btn_PickServices");

    /// <summary>Remove</summary>
    public static string Editor_Btn_RemoveEntry => Get("Editor_Btn_RemoveEntry");

    /// <summary>Use all processors</summary>
    public static string Editor_Chk_AllProcessors => Get("Editor_Chk_AllProcessors");

    /// <summary>Append to existing files (instead of clearing them at start)</summary>
    public static string Editor_Chk_Append => Get("Editor_Chk_Append");

    /// <summary>Allow the service to interact with the desktop</summary>
    public static string Editor_Chk_Interact => Get("Editor_Chk_Interact");

    /// <summary>Also terminate all child processes (process tree)</summary>
    public static string Editor_Chk_KillTree => Get("Editor_Chk_KillTree");

    /// <summary>Log EasyService events (start, crash, restart)</summary>
    public static string Editor_Chk_LogEvents => Get("Editor_Chk_LogEvents");

    /// <summary>Report this service to the monitoring</summary>
    public static string Editor_Chk_MonitoringEnabled => Get("Editor_Chk_MonitoringEnabled");

    /// <summary>Replace the existing environment entirely</summary>
    public static string Editor_Chk_ReplaceEnvironment => Get("Editor_Chk_ReplaceEnvironment");

    /// <summary>Rotate logs automatically</summary>
    public static string Editor_Chk_Rotate => Get("Editor_Chk_Rotate");

    /// <summary>Start the service after creating it</summary>
    public static string Editor_Chk_StartAfterSave => Get("Editor_Chk_StartAfterSave");

    /// <summary>Send Ctrl+C (console applications)</summary>
    public static string Editor_Chk_StopConsole => Get("Editor_Chk_StopConsole");

    /// <summary>Terminate the process if necessary</summary>
    public static string Editor_Chk_StopTerminate => Get("Editor_Chk_StopTerminate");

    /// <summary>Send WM_QUIT to threads</summary>
    public static string Editor_Chk_StopThreads => Get("Editor_Chk_StopThreads");

    /// <summary>Send WM_CLOSE to windows</summary>
    public static string Editor_Chk_StopWindow => Get("Editor_Chk_StopWindow");

    /// <summary>Prefix every line with a timestamp</summary>
    public static string Editor_Chk_Timestamp => Get("Editor_Chk_Timestamp");

    /// <summary>CPU {0}</summary>
    public static string Editor_Cpu(object? p0) => Fmt("Editor_Cpu", p0);

    /// <summary>At least one processor must be selected.</summary>
    public static string Editor_Err_NoProcessor => Get("Editor_Err_NoProcessor");

    /// <summary>At least one method for stopping the application must be enabled.</summary>
    public static string Editor_Err_NoStopMethod => Get("Editor_Err_NoStopMethod");

    /// <summary>Exit code {0} -&gt; {1}</summary>
    public static string Editor_ExitCodeEntry(object? p0, object? p1) => Fmt("Editor_ExitCodeEntry", p0, p1);

    /// <summary>Do nothing</summary>
    public static string Editor_ExitShort_Ignore => Get("Editor_ExitShort_Ignore");

    /// <summary>Restart</summary>
    public static string Editor_ExitShort_Restart => Get("Editor_ExitShort_Restart");

    /// <summary>Stop the service</summary>
    public static string Editor_ExitShort_Stop => Get("Editor_ExitShort_Stop");

    /// <summary>Do nothing (service stays up)</summary>
    public static string Editor_Exit_Ignore => Get("Editor_Exit_Ignore");

    /// <summary>Restart the application</summary>
    public static string Editor_Exit_Restart => Get("Editor_Exit_Restart");

    /// <summary>Stop the service</summary>
    public static string Editor_Exit_Stop => Get("Editor_Exit_Stop");

    /// <summary>Diagnostics</summary>
    public static string Editor_Group_Diagnostics => Get("Editor_Group_Diagnostics");

    /// <summary>Actions for individual exit codes</summary>
    public static string Editor_Group_ExitCodes => Get("Editor_Group_ExitCodes");

    /// <summary>Connecting to your monitoring</summary>
    public static string Editor_Group_Integration => Get("Editor_Group_Integration");

    /// <summary>Process</summary>
    public static string Editor_Group_Process => Get("Editor_Group_Process");

    /// <summary>Rotation</summary>
    public static string Editor_Group_Rotation => Get("Editor_Group_Rotation");

    /// <summary>Thresholds</summary>
    public static string Editor_Group_Thresholds => Get("Editor_Group_Thresholds");

    /// <summary>Checking...</summary>
    public static string Editor_Health_Testing => Get("Editor_Health_Testing");

    /// <summary>Format: DOMAIN\User, or .\User for local accounts. EasyService grants the account the "Log on as a service" right automatically.</summary>
    public static string Editor_Hint_Account => Get("Editor_Hint_Account");

    /// <summary>Arguments are passed to the program unchanged. Please quote paths that contain spaces.</summary>
    public static string Editor_Hint_Arguments => Get("Editor_Hint_Arguments");

    /// <summary>100 % means every core of the machine is fully busy.</summary>
    public static string Editor_Hint_Cpu100 => Get("Editor_Hint_Cpu100");

    /// <summary>Services that have to run before this one - one name per line. Windows only starts the service once all of them are running.</summary>
    public static string Editor_Hint_Dependencies => Get("Editor_Hint_Dependencies");

    /// <summary>Additional environment variables for the application - one per line in the form NAME=VALUE. Existing variables such as %PATH% can be used.</summary>
    public static string Editor_Hint_Environment => Get("Editor_Hint_Environment");

    /// <summary>What should happen when the application exits by itself?</summary>
    public static string Editor_Hint_Exit => Get("Editor_Hint_Exit");

    /// <summary>Example: set exit code 0 to "Stop the service" so a program that finished cleanly is not restarted forever.</summary>
    public static string Editor_Hint_ExitCodes => Get("Editor_Hint_ExitCodes");

    /// <summary>Windows only knows whether the process exists. An application that has deadlocked or lost its database still looks healthy to it. A check asks the applicatio...</summary>
    public static string Editor_Hint_Health => Get("Editor_Hint_Health");

    /// <summary>A command line. Exit code 0 means healthy. Runs as the service account.</summary>
    public static string Editor_Hint_HealthCommand => Get("Editor_Hint_HealthCommand");

    /// <summary>0 accepts anything from 200 to 299.</summary>
    public static string Editor_Hint_HealthExpect => Get("Editor_Hint_HealthExpect");

    /// <summary>A file the application keeps writing to - a heartbeat file, or its own log.</summary>
    public static string Editor_Hint_HealthFile => Get("Editor_Hint_HealthFile");

    /// <summary>For example http://localhost:8080/health - the certificate is not verified, the question is whether the application answers.</summary>
    public static string Editor_Hint_HealthHttp => Get("Editor_Hint_HealthHttp");

    /// <summary>For example localhost:5432</summary>
    public static string Editor_Hint_HealthTcp => Get("Editor_Hint_HealthTcp");

    /// <summary>0 = record no history. One row per minute, about 80 KB per service and day, stored as CSV under %ProgramData%\EasyService\history.</summary>
    public static string Editor_Hint_HistoryDays => Get("Editor_Hint_HistoryDays");

    /// <summary>Only possible with the local system account. Modern Windows versions isolate services in session 0; windows of the application are not visible to logged-on u...</summary>
    public static string Editor_Hint_Interact => Get("Editor_Hint_Interact");

    /// <summary>Leave empty to keep the stored password.</summary>
    public static string Editor_Hint_KeepPassword => Get("Editor_Hint_KeepPassword");

    /// <summary>Everything the application writes to stdout and stderr ends up in these files. If both point at the same file, the streams are merged.</summary>
    public static string Editor_Hint_Logging => Get("Editor_Hint_Logging");

    /// <summary>The whole process tree is measured, not just the main process.</summary>
    public static string Editor_Hint_Memory => Get("Editor_Hint_Memory");

    /// <summary>Windows reports a service as "running" as long as EasyService itself is alive - even when the application behind it crashes every minute. EasyService therefo...</summary>
    public static string Editor_Hint_Monitoring => Get("Editor_Hint_Monitoring");

    /// <summary>Without a hard terminate a hung process can block Windows from shutting down.</summary>
    public static string Editor_Hint_NoTerminate => Get("Editor_Hint_NoTerminate");

    /// <summary>Careful: when replacing, the application only receives the variables listed above. Without PATH and SystemRoot many programs will not start.</summary>
    public static string Editor_Hint_ReplaceEnvironment => Get("Editor_Hint_ReplaceEnvironment");

    /// <summary>0 hours = rotate by size only.</summary>
    public static string Editor_Hint_RotateHours => Get("Editor_Hint_RotateHours");

    /// <summary>0 = never delete old logs.</summary>
    public static string Editor_Hint_RotateKeep => Get("Editor_Hint_RotateKeep");

    /// <summary>Internal name Windows uses for the service. Cannot be changed after creation.</summary>
    public static string Editor_Hint_ServiceName => Get("Editor_Hint_ServiceName");

    /// <summary>When the service stops, EasyService tries to close the application gracefully in stages. Every enabled stage waits the given time before the next one follows.</summary>
    public static string Editor_Hint_Shutdown => Get("Editor_Hint_Shutdown");

    /// <summary>Time to wait before the application is launched for the first time after the service starts.</summary>
    public static string Editor_Hint_StartupDelay => Get("Editor_Hint_StartupDelay");

    /// <summary>If the application exits faster than the throttle window, EasyService doubles the wait before each further attempt (up to 60 s). That prevents restart loops ...</summary>
    public static string Editor_Hint_Throttle => Get("Editor_Hint_Throttle");

    /// <summary>0 means: do not check this value.</summary>
    public static string Editor_Hint_ZeroOff => Get("Editor_Hint_ZeroOff");

    /// <summary>Checkmk - all monitored services in one local check:</summary>
    public static string Editor_Integration_Checkmk => Get("Editor_Integration_Checkmk");

    /// <summary>Content: {0}</summary>
    public static string Editor_Integration_Content(object? p0) => Fmt("Editor_Integration_Content", p0);

    /// <summary>File: {0}</summary>
    public static string Editor_Integration_File(object? p0) => Fmt("Editor_Integration_File", p0);

    /// <summary>Any tool - complete state as JSON:</summary>
    public static string Editor_Integration_Json => Get("Editor_Integration_Json");

    /// <summary>Nagios / Icinga - one service, exit code 0/1/2/3:</summary>
    public static string Editor_Integration_Nagios => Get("Editor_Integration_Nagios");

    /// <summary>Prometheus - textfile collector of node_exporter, e.g. every minute via Task Scheduler:</summary>
    public static string Editor_Integration_Prometheus => Get("Editor_Integration_Prometheus");

    /// <summary>Zabbix - in zabbix_agentd.conf:</summary>
    public static string Editor_Integration_Zabbix => Get("Editor_Integration_Zabbix");

    /// <summary>Account:</summary>
    public static string Editor_Lbl_Account => Get("Editor_Lbl_Account");

    /// <summary>Arguments:</summary>
    public static string Editor_Lbl_Arguments => Get("Editor_Lbl_Arguments");

    /// <summary>CPU in % - critical:</summary>
    public static string Editor_Lbl_CritCpu => Get("Editor_Lbl_CritCpu");

    /// <summary>Memory MB - critical:</summary>
    public static string Editor_Lbl_CritMemory => Get("Editor_Lbl_CritMemory");

    /// <summary>Restarts/hour - critical:</summary>
    public static string Editor_Lbl_CritRestarts => Get("Editor_Lbl_CritRestarts");

    /// <summary>Default action:</summary>
    public static string Editor_Lbl_DefaultExit => Get("Editor_Lbl_DefaultExit");

    /// <summary>Description:</summary>
    public static string Editor_Lbl_Description => Get("Editor_Lbl_Description");

    /// <summary>Startup directory:</summary>
    public static string Editor_Lbl_Directory => Get("Editor_Lbl_Directory");

    /// <summary>Display name:</summary>
    public static string Editor_Lbl_DisplayName => Get("Editor_Lbl_DisplayName");

    /// <summary>Exit code:</summary>
    public static string Editor_Lbl_ExitCode => Get("Editor_Lbl_ExitCode");

    /// <summary>Then:</summary>
    public static string Editor_Lbl_HealthAction => Get("Editor_Lbl_HealthAction");

    /// <summary>Expected status:</summary>
    public static string Editor_Lbl_HealthExpect => Get("Editor_Lbl_HealthExpect");

    /// <summary>Failures in a row:</summary>
    public static string Editor_Lbl_HealthFailures => Get("Editor_Lbl_HealthFailures");

    /// <summary>Grace after start (ms):</summary>
    public static string Editor_Lbl_HealthGrace => Get("Editor_Lbl_HealthGrace");

    /// <summary>Every (ms):</summary>
    public static string Editor_Lbl_HealthInterval => Get("Editor_Lbl_HealthInterval");

    /// <summary>File at most (s) old:</summary>
    public static string Editor_Lbl_HealthMaxAge => Get("Editor_Lbl_HealthMaxAge");

    /// <summary>Target:</summary>
    public static string Editor_Lbl_HealthTarget => Get("Editor_Lbl_HealthTarget");

    /// <summary>Timeout (ms):</summary>
    public static string Editor_Lbl_HealthTimeout => Get("Editor_Lbl_HealthTimeout");

    /// <summary>Check:</summary>
    public static string Editor_Lbl_HealthType => Get("Editor_Lbl_HealthType");

    /// <summary>Keep history (days):</summary>
    public static string Editor_Lbl_HistoryDays => Get("Editor_Lbl_HistoryDays");

    /// <summary>Log on as:</summary>
    public static string Editor_Lbl_LogonAs => Get("Editor_Lbl_LogonAs");

    /// <summary>Password:</summary>
    public static string Editor_Lbl_Password => Get("Editor_Lbl_Password");

    /// <summary>Priority:</summary>
    public static string Editor_Lbl_Priority => Get("Editor_Lbl_Priority");

    /// <summary>Processors:</summary>
    public static string Editor_Lbl_Processors => Get("Editor_Lbl_Processors");

    /// <summary>Program:</summary>
    public static string Editor_Lbl_Program => Get("Editor_Lbl_Program");

    /// <summary>Delay (ms):</summary>
    public static string Editor_Lbl_RestartDelay => Get("Editor_Lbl_RestartDelay");

    /// <summary>Rotate every (hours):</summary>
    public static string Editor_Lbl_RotateHours => Get("Editor_Lbl_RotateHours");

    /// <summary>Archives to keep:</summary>
    public static string Editor_Lbl_RotateKeep => Get("Editor_Lbl_RotateKeep");

    /// <summary>Rotate at (MB):</summary>
    public static string Editor_Lbl_RotateMb => Get("Editor_Lbl_RotateMb");

    /// <summary>Service name:</summary>
    public static string Editor_Lbl_ServiceName => Get("Editor_Lbl_ServiceName");

    /// <summary>Startup type:</summary>
    public static string Editor_Lbl_Startup => Get("Editor_Lbl_Startup");

    /// <summary>Startup delay (ms):</summary>
    public static string Editor_Lbl_StartupDelay => Get("Editor_Lbl_StartupDelay");

    /// <summary>Errors (stderr):</summary>
    public static string Editor_Lbl_Stderr => Get("Editor_Lbl_Stderr");

    /// <summary>Output (stdout):</summary>
    public static string Editor_Lbl_Stdout => Get("Editor_Lbl_Stdout");

    /// <summary>Throttle window (ms):</summary>
    public static string Editor_Lbl_Throttle => Get("Editor_Lbl_Throttle");

    /// <summary>Wait (ms):</summary>
    public static string Editor_Lbl_WaitMs => Get("Editor_Lbl_WaitMs");

    /// <summary>CPU in % - warning:</summary>
    public static string Editor_Lbl_WarnCpu => Get("Editor_Lbl_WarnCpu");

    /// <summary>Memory MB - warning:</summary>
    public static string Editor_Lbl_WarnMemory => Get("Editor_Lbl_WarnMemory");

    /// <summary>Restarts/hour - warning:</summary>
    public static string Editor_Lbl_WarnRestarts => Get("Editor_Lbl_WarnRestarts");

    /// <summary>This account</summary>
    public static string Editor_Logon_Account => Get("Editor_Logon_Account");

    /// <summary>Local service</summary>
    public static string Editor_Logon_LocalService => Get("Editor_Logon_LocalService");

    /// <summary>Local system account</summary>
    public static string Editor_Logon_LocalSystem => Get("Editor_Logon_LocalSystem");

    /// <summary>Network service</summary>
    public static string Editor_Logon_NetworkService => Get("Editor_Logon_NetworkService");

    /// <summary>Filter...</summary>
    public static string Editor_Picker_Filter => Get("Editor_Picker_Filter");

    /// <summary>Select dependencies</summary>
    public static string Editor_Picker_Title => Get("Editor_Picker_Title");

    /// <summary>Above normal</summary>
    public static string Editor_Prio_AboveNormal => Get("Editor_Prio_AboveNormal");

    /// <summary>Below normal</summary>
    public static string Editor_Prio_BelowNormal => Get("Editor_Prio_BelowNormal");

    /// <summary>High</summary>
    public static string Editor_Prio_High => Get("Editor_Prio_High");

    /// <summary>Low</summary>
    public static string Editor_Prio_Idle => Get("Editor_Prio_Idle");

    /// <summary>Normal</summary>
    public static string Editor_Prio_Normal => Get("Editor_Prio_Normal");

    /// <summary>Realtime</summary>
    public static string Editor_Prio_Realtime => Get("Editor_Prio_Realtime");

    /// <summary>Automatic (delayed start)</summary>
    public static string Editor_Startup_AutoDelayed => Get("Editor_Startup_AutoDelayed");

    /// <summary>Application</summary>
    public static string Editor_Tab_Application => Get("Editor_Tab_Application");

    /// <summary>Dependencies</summary>
    public static string Editor_Tab_Dependencies => Get("Editor_Tab_Dependencies");

    /// <summary>Details</summary>
    public static string Editor_Tab_Details => Get("Editor_Tab_Details");

    /// <summary>Environment</summary>
    public static string Editor_Tab_Environment => Get("Editor_Tab_Environment");

    /// <summary>Exit actions</summary>
    public static string Editor_Tab_Exit => Get("Editor_Tab_Exit");

    /// <summary>Health check</summary>
    public static string Editor_Tab_Health => Get("Editor_Tab_Health");

    /// <summary>Log on</summary>
    public static string Editor_Tab_LogOn => Get("Editor_Tab_LogOn");

    /// <summary>Logging</summary>
    public static string Editor_Tab_Logging => Get("Editor_Tab_Logging");

    /// <summary>Monitoring</summary>
    public static string Editor_Tab_Monitoring => Get("Editor_Tab_Monitoring");

    /// <summary>Shutdown</summary>
    public static string Editor_Tab_Shutdown => Get("Editor_Tab_Shutdown");

    /// <summary>Edit service - {0}</summary>
    public static string Editor_Title_Edit(object? p0) => Fmt("Editor_Title_Edit", p0);

    /// <summary>Create a new service</summary>
    public static string Editor_Title_New => Get("Editor_Title_New");

    /// <summary>Application exited</summary>
    public static string Evt_ApplicationExited => Get("Evt_ApplicationExited");

    /// <summary>Application is restarting</summary>
    public static string Evt_ApplicationRestarting => Get("Evt_ApplicationRestarting");

    /// <summary>Start failed</summary>
    public static string Evt_ApplicationStartFailed => Get("Evt_ApplicationStartFailed");

    /// <summary>Application started</summary>
    public static string Evt_ApplicationStarted => Get("Evt_ApplicationStarted");

    /// <summary>Application terminated</summary>
    public static string Evt_ApplicationTerminated => Get("Evt_ApplicationTerminated");

    /// <summary>Configuration problem</summary>
    public static string Evt_ConfigurationProblem => Get("Evt_ConfigurationProblem");

    /// <summary>Health check failed</summary>
    public static string Evt_HealthCheckFailed => Get("Evt_HealthCheckFailed");

    /// <summary>Health check recovered</summary>
    public static string Evt_HealthCheckRecovered => Get("Evt_HealthCheckRecovered");

    /// <summary>Restarted by the health check</summary>
    public static string Evt_HealthCheckRestarted => Get("Evt_HealthCheckRestarted");

    /// <summary>Logging problem</summary>
    public static string Evt_LoggingProblem => Get("Evt_LoggingProblem");

    /// <summary>Restart throttled</summary>
    public static string Evt_RestartThrottled => Get("Evt_RestartThrottled");

    /// <summary>Service is stopping</summary>
    public static string Evt_ServiceStopping => Get("Evt_ServiceStopping");

    /// <summary>Stopped by exit action</summary>
    public static string Evt_StoppedByExitPolicy => Get("Evt_StoppedByExitPolicy");

    /// <summary>Supervision started</summary>
    public static string Evt_SupervisorStarted => Get("Evt_SupervisorStarted");

    /// <summary>only report it</summary>
    public static string Health_Action_Report => Get("Health_Action_Report");

    /// <summary>restart the application</summary>
    public static string Health_Action_Restart => Get("Health_Action_Restart");

    /// <summary>Exit code {0}: {1}</summary>
    public static string Health_CommandExit(object? p0, object? p1) => Fmt("Health_CommandExit", p0, p1);

    /// <summary>Written {0} s ago</summary>
    public static string Health_FileFresh(object? p0) => Fmt("Health_FileFresh", p0);

    /// <summary>File does not exist: {0}</summary>
    public static string Health_FileMissing(object? p0) => Fmt("Health_FileMissing", p0);

    /// <summary>Untouched for {0} s, allowed are {1} s</summary>
    public static string Health_FileStale(object? p0, object? p1) => Fmt("Health_FileStale", p0, p1);

    /// <summary>HTTP {0} {1}</summary>
    public static string Health_HttpStatus(object? p0, object? p1) => Fmt("Health_HttpStatus", p0, p1);

    /// <summary>No health check configured</summary>
    public static string Health_NotConfigured => Get("Health_NotConfigured");

    /// <summary>{0}:{1} accepts connections</summary>
    public static string Health_TcpOpen(object? p0, object? p1) => Fmt("Health_TcpOpen", p0, p1);

    /// <summary>{0}:{1} not reachable ({2})</summary>
    public static string Health_TcpRefused(object? p0, object? p1, object? p2) => Fmt("Health_TcpRefused", p0, p1, p2);

    /// <summary>No answer within {0} ms</summary>
    public static string Health_Timeout(object? p0) => Fmt("Health_Timeout", p0);

    /// <summary>Run a program, exit code 0</summary>
    public static string Health_Type_Command => Get("Health_Type_Command");

    /// <summary>File was written recently</summary>
    public static string Health_Type_File => Get("Health_Type_File");

    /// <summary>Fetch a URL</summary>
    public static string Health_Type_Http => Get("Health_Type_Http");

    /// <summary>No check</summary>
    public static string Health_Type_None => Get("Health_Type_None");

    /// <summary>Open a TCP port</summary>
    public static string Health_Type_Tcp => Get("Health_Type_Tcp");

    /// <summary>Export CSV...</summary>
    public static string Hist_Btn_Export => Get("Hist_Btn_Export");

    /// <summary>Open folder</summary>
    public static string Hist_Btn_OpenFolder => Get("Hist_Btn_OpenFolder");

    /// <summary>CPU load in % — line: average per minute, band: peak</summary>
    public static string Hist_Chart_Cpu => Get("Hist_Chart_Cpu");

    /// <summary>Memory — line: average per minute, band: peak</summary>
    public static string Hist_Chart_Memory => Get("Hist_Chart_Memory");

    /// <summary>Detail</summary>
    public static string Hist_Col_Detail => Get("Hist_Col_Detail");

    /// <summary>Event</summary>
    public static string Hist_Col_Event => Get("Hist_Col_Event");

    /// <summary>Exit code</summary>
    public static string Hist_Col_ExitCode => Get("Hist_Col_ExitCode");

    /// <summary>Time</summary>
    public static string Hist_Col_Time => Get("Hist_Col_Time");

    /// <summary>The history is switched off for this service (Monitoring tab).</summary>
    public static string Hist_Disabled => Get("Hist_Disabled");

    /// <summary>No measurements for this period yet.</summary>
    public static string Hist_Empty => Get("Hist_Empty");

    /// <summary>Export failed</summary>
    public static string Hist_Export_Failed => Get("Hist_Export_Failed");

    /// <summary>Exported: {0}</summary>
    public static string Hist_Exported(object? p0) => Fmt("Hist_Exported", p0);

    /// <summary>Events</summary>
    public static string Hist_Group_Events => Get("Hist_Group_Events");

    /// <summary>Period:</summary>
    public static string Hist_Lbl_Range => Get("Hist_Lbl_Range");

    /// <summary>Dotted vertical lines mark application starts.</summary>
    public static string Hist_MarkerLegend => Get("Hist_MarkerLegend");

    /// <summary>No events in this period.</summary>
    public static string Hist_NoEvents => Get("Hist_NoEvents");

    /// <summary>Last hour</summary>
    public static string Hist_Range_1h => Get("Hist_Range_1h");

    /// <summary>Last 24 hours</summary>
    public static string Hist_Range_24h => Get("Hist_Range_24h");

    /// <summary>Last 30 days</summary>
    public static string Hist_Range_30d => Get("Hist_Range_30d");

    /// <summary>Last 7 days</summary>
    public static string Hist_Range_7d => Get("Hist_Range_7d");

    /// <summary>Period covered</summary>
    public static string Hist_Stat_Covered => Get("Hist_Stat_Covered");

    /// <summary>CPU average</summary>
    public static string Hist_Stat_CpuAvg => Get("Hist_Stat_CpuAvg");

    /// <summary>CPU peak</summary>
    public static string Hist_Stat_CpuPeak => Get("Hist_Stat_CpuPeak");

    /// <summary>Memory average</summary>
    public static string Hist_Stat_MemAvg => Get("Hist_Stat_MemAvg");

    /// <summary>Memory peak</summary>
    public static string Hist_Stat_MemPeak => Get("Hist_Stat_MemPeak");

    /// <summary>Restarts</summary>
    public static string Hist_Stat_Restarts => Get("Hist_Stat_Restarts");

    /// <summary>{0} measurements, {1} events</summary>
    public static string Hist_Status(object? p0, object? p1) => Fmt("Hist_Status", p0, p1);

    /// <summary>History - {0}</summary>
    public static string Hist_Title(object? p0) => Fmt("Hist_Title", p0);

    /// <summary>The configuration could not be read: {0}</summary>
    public static string Host_ConfigReadFailed(object? p0) => Fmt("Host_ConfigReadFailed", p0);

    /// <summary>The service stopped because of an error: {0}</summary>
    public static string Host_Crashed(object? p0) => Fmt("Host_Crashed", p0);

    /// <summary>StartServiceCtrlDispatcher failed ({0}). "easyservice.exe run &lt;service&gt;" is only meant to be started by the service control manager.</summary>
    public static string Host_DispatcherFailed(object? p0) => Fmt("Host_DispatcherFailed", p0);

    /// <summary>No EasyService configuration is stored for this service (HKLM\SYSTEM\CurrentControlSet\Services\{0}\Parameters).</summary>
    public static string Host_NoConfig(object? p0) => Fmt("Host_NoConfig", p0);

    /// <summary>Error while stopping: {0}</summary>
    public static string Host_StopFailed(object? p0) => Fmt("Host_StopFailed", p0);

    /// <summary>Unexpected error: {0}</summary>
    public static string Host_Unexpected(object? p0) => Fmt("Host_Unexpected", p0);

    /// <summary>Clear</summary>
    public static string Log_Btn_Clear => Get("Log_Btn_Clear");

    /// <summary>Open Event Viewer</summary>
    public static string Log_Btn_EventViewer => Get("Log_Btn_EventViewer");

    /// <summary>Follow</summary>
    public static string Log_Btn_Follow => Get("Log_Btn_Follow");

    /// <summary>Open folder</summary>
    public static string Log_Btn_OpenFolder => Get("Log_Btn_OpenFolder");

    /// <summary>Refresh</summary>
    public static string Log_Btn_RefreshEvents => Get("Log_Btn_RefreshEvents");

    /// <summary>Reload</summary>
    public static string Log_Btn_Reload => Get("Log_Btn_Reload");

    /// <summary>Save as...</summary>
    public static string Log_Btn_SaveAs => Get("Log_Btn_SaveAs");

    /// <summary>Clearing failed</summary>
    public static string Log_Clear_Failed => Get("Log_Clear_Failed");

    /// <summary>The file is locked. Please stop the service and try again. {0}</summary>
    public static string Log_Clear_Locked(object? p0) => Fmt("Log_Clear_Locked", p0);

    /// <summary>The contents of {0} will be deleted. Continue?</summary>
    public static string Log_Clear_Text(object? p0) => Fmt("Log_Clear_Text", p0);

    /// <summary>Clear log</summary>
    public static string Log_Clear_Title => Get("Log_Clear_Title");

    /// <summary>Event</summary>
    public static string Log_Col_Event => Get("Log_Col_Event");

    /// <summary>ID</summary>
    public static string Log_Col_Id => Get("Log_Col_Id");

    /// <summary>Message</summary>
    public static string Log_Col_Message => Get("Log_Col_Message");

    /// <summary>Time</summary>
    public static string Log_Col_Time => Get("Log_Col_Time");

    /// <summary>Type</summary>
    public static string Log_Col_Type => Get("Log_Col_Type");

    /// <summary>{0} (current)</summary>
    public static string Log_Current(object? p0) => Fmt("Log_Current", p0);

    /// <summary>{0}: {1}</summary>
    public static string Log_Entry(object? p0, object? p1) => Fmt("Log_Entry", p0, p1);

    /// <summary>Event Viewer</summary>
    public static string Log_EventViewer => Get("Log_EventViewer");

    /// <summary>File:</summary>
    public static string Log_Lbl_File => Get("Log_Lbl_File");

    /// <summary>Filter:</summary>
    public static string Log_Lbl_Filter => Get("Log_Lbl_Filter");

    /// <summary>No EasyService entries found in the application log.</summary>
    public static string Log_NoEvents => Get("Log_NoEvents");

    /// <summary>No log files have been created for this service yet.</summary>
    public static string Log_NoFiles => Get("Log_NoFiles");

    /// <summary>File not found: {0}</summary>
    public static string Log_NotFound(object? p0) => Fmt("Log_NotFound", p0);

    /// <summary>Saving failed</summary>
    public static string Log_SaveFailed => Get("Log_SaveFailed");

    /// <summary>Saved: {0}</summary>
    public static string Log_Saved(object? p0) => Fmt("Log_Saved", p0);

    /// <summary>- {0} KB</summary>
    public static string Log_Size(object? p0) => Fmt("Log_Size", p0);

    /// <summary>{0} of {1} lines (filtered){2} - {3}</summary>
    public static string Log_Status_Filtered(object? p0, object? p1, object? p2, object? p3) => Fmt("Log_Status_Filtered", p0, p1, p2, p3);

    /// <summary>{0} lines{1} - {2}</summary>
    public static string Log_Status_Plain(object? p0, object? p1, object? p2) => Fmt("Log_Status_Plain", p0, p1, p2);

    /// <summary>Windows events</summary>
    public static string Log_Tab_Events => Get("Log_Tab_Events");

    /// <summary>Log file</summary>
    public static string Log_Tab_File => Get("Log_Tab_File");

    /// <summary>Show new lines automatically</summary>
    public static string Log_Tip_Follow => Get("Log_Tip_Follow");

    /// <summary>Logs - {0}</summary>
    public static string Log_Title(object? p0) => Fmt("Log_Title", p0);

    /// <summary>Add service...</summary>
    public static string Main_Btn_Add => Get("Main_Btn_Add");

    /// <summary>Details</summary>
    public static string Main_Btn_Details => Get("Main_Btn_Details");

    /// <summary>Duplicate...</summary>
    public static string Main_Btn_Duplicate => Get("Main_Btn_Duplicate");

    /// <summary>Edit...</summary>
    public static string Main_Btn_Edit => Get("Main_Btn_Edit");

    /// <summary>Export...</summary>
    public static string Main_Btn_Export => Get("Main_Btn_Export");

    /// <summary>Export all...</summary>
    public static string Main_Btn_ExportAll => Get("Main_Btn_ExportAll");

    /// <summary>History...</summary>
    public static string Main_Btn_History => Get("Main_Btn_History");

    /// <summary>Import...</summary>
    public static string Main_Btn_Import => Get("Main_Btn_Import");

    /// <summary>Logs...</summary>
    public static string Main_Btn_Logs => Get("Main_Btn_Logs");

    /// <summary>EasyService only</summary>
    public static string Main_Btn_OnlyManaged => Get("Main_Btn_OnlyManaged");

    /// <summary>Refresh</summary>
    public static string Main_Btn_Refresh => Get("Main_Btn_Refresh");

    /// <summary>Remove</summary>
    public static string Main_Btn_Remove => Get("Main_Btn_Remove");

    /// <summary>Restart</summary>
    public static string Main_Btn_Restart => Get("Main_Btn_Restart");

    /// <summary>Start</summary>
    public static string Main_Btn_Start => Get("Main_Btn_Start");

    /// <summary>Stop</summary>
    public static string Main_Btn_Stop => Get("Main_Btn_Stop");

    /// <summary>{0} of {1} done.</summary>
    public static string Main_Bulk_Done(object? p0, object? p1) => Fmt("Main_Bulk_Done", p0, p1);

    /// <summary>Not everything worked</summary>
    public static string Main_Bulk_Failed => Get("Main_Bulk_Failed");

    /// <summary>Restart {0} selected services?</summary>
    public static string Main_Bulk_Restart(object? p0) => Fmt("Main_Bulk_Restart", p0);

    /// <summary>Start {0} selected services?</summary>
    public static string Main_Bulk_Start(object? p0) => Fmt("Main_Bulk_Start", p0);

    /// <summary>Stop {0} selected services?</summary>
    public static string Main_Bulk_Stop(object? p0) => Fmt("Main_Bulk_Stop", p0);

    /// <summary>Several services</summary>
    public static string Main_Bulk_Title => Get("Main_Bulk_Title");

    /// <summary>Account</summary>
    public static string Main_Col_Account => Get("Main_Col_Account");

    /// <summary>Application</summary>
    public static string Main_Col_Application => Get("Main_Col_Application");

    /// <summary>CPU</summary>
    public static string Main_Col_Cpu => Get("Main_Col_Cpu");

    /// <summary>Display name</summary>
    public static string Main_Col_DisplayName => Get("Main_Col_DisplayName");

    /// <summary>Name</summary>
    public static string Main_Col_Name => Get("Main_Col_Name");

    /// <summary>PID</summary>
    public static string Main_Col_Pid => Get("Main_Col_Pid");

    /// <summary>Program</summary>
    public static string Main_Col_Program => Get("Main_Col_Program");

    /// <summary>RAM</summary>
    public static string Main_Col_Ram => Get("Main_Col_Ram");

    /// <summary>Restarts/h</summary>
    public static string Main_Col_Restarts => Get("Main_Col_Restarts");

    /// <summary>Startup</summary>
    public static string Main_Col_Startup => Get("Main_Col_Startup");

    /// <summary>Status</summary>
    public static string Main_Col_Status => Get("Main_Col_Status");

    /// <summary>Uptime</summary>
    public static string Main_Col_Uptime => Get("Main_Col_Uptime");

    /// <summary>Open program folder</summary>
    public static string Main_Ctx_OpenFolder => Get("Main_Ctx_OpenFolder");

    /// <summary>Show in services.msc</summary>
    public static string Main_Ctx_ServicesMsc => Get("Main_Ctx_ServicesMsc");

    /// <summary>No service matches “{0}”. Clear the filter, or switch off “{1}” to see every Windows service.</summary>
    public static string Main_Empty_Filter_Text(object? p0, object? p1) => Fmt("Main_Empty_Filter_Text", p0, p1);

    /// <summary>Nothing matches</summary>
    public static string Main_Empty_Filter_Title => Get("Main_Empty_Filter_Title");

    /// <summary>EasyService runs a program as a Windows service: started at boot, restarted after a crash, its output written to a log file and its state handed to your moni...</summary>
    public static string Main_Empty_Text => Get("Main_Empty_Text");

    /// <summary>No services yet</summary>
    public static string Main_Empty_Title => Get("Main_Empty_Title");

    /// <summary>Services could not be read</summary>
    public static string Main_Err_ListFailed => Get("Main_Err_ListFailed");

    /// <summary>The language changes the next time EasyService is started.</summary>
    public static string Main_Language_Restart => Get("Main_Language_Restart");

    /// <summary>Filter:</summary>
    public static string Main_Lbl_Filter => Get("Main_Lbl_Filter");

    /// <summary>Configuration</summary>
    public static string Main_Menu_Config => Get("Main_Menu_Config");

    /// <summary>Language</summary>
    public static string Main_Menu_Language => Get("Main_Menu_Language");

    /// <summary>Automatic (system)</summary>
    public static string Main_Menu_LanguageAuto => Get("Main_Menu_LanguageAuto");

    /// <summary>No EasyService configuration is stored for "{0}".</summary>
    public static string Main_MissingConfig_Text(object? p0) => Fmt("Main_MissingConfig_Text", p0);

    /// <summary>Configuration missing</summary>
    public static string Main_MissingConfig_Title => Get("Main_MissingConfig_Title");

    /// <summary>No logs</summary>
    public static string Main_NoLogs_Title => Get("Main_NoLogs_Title");

    /// <summary>"{0}" was not created with EasyService and cannot be edited here. EasyService only edits the services it manages itself, so that foreign services cannot be d...</summary>
    public static string Main_NotEditable_Text(object? p0) => Fmt("Main_NotEditable_Text", p0);

    /// <summary>Cannot be edited</summary>
    public static string Main_NotEditable_Title => Get("Main_NotEditable_Title");

    /// <summary>WARNING: "{0}" was NOT created with EasyService. Removing a foreign system service can render Windows or installed software unusable. Really remove it?</summary>
    public static string Main_Remove_Foreign(object? p0) => Fmt("Main_Remove_Foreign", p0);

    /// <summary>The service "{0}" will be stopped and permanently removed. The log files are kept.</summary>
    public static string Main_Remove_Managed(object? p0) => Fmt("Main_Remove_Managed", p0);

    /// <summary>These {0} services will be removed: {1} Continue?</summary>
    public static string Main_Remove_Many(object? p0, object? p1) => Fmt("Main_Remove_Many", p0, p1);

    /// <summary>Remove service</summary>
    public static string Main_Remove_Title => Get("Main_Remove_Title");

    /// <summary>The changes to "{0}" only take effect after the service is restarted. Restart now?</summary>
    public static string Main_Restart_Text(object? p0) => Fmt("Main_Restart_Text", p0);

    /// <summary>Restart?</summary>
    public static string Main_Restart_Title => Get("Main_Restart_Title");

    /// <summary>The service "{0}" was created but could not be started. The cause is usually in the log. Open it now?</summary>
    public static string Main_StartFailed_Text(object? p0) => Fmt("Main_StartFailed_Text", p0);

    /// <summary>Start failed</summary>
    public static string Main_StartFailed_Title => Get("Main_StartFailed_Title");

    /// <summary>- all healthy</summary>
    public static string Main_Status_AllFine => Get("Main_Status_AllFine");

    /// <summary>Error: {0}</summary>
    public static string Main_Status_Error(object? p0) => Fmt("Main_Status_Error", p0);

    /// <summary>- {0} critical, {1} warning</summary>
    public static string Main_Status_Health(object? p0, object? p1) => Fmt("Main_Status_Health", p0, p1);

    /// <summary>Reading services...</summary>
    public static string Main_Status_Loading => Get("Main_Status_Loading");

    /// <summary>{0} of {1} services shown - {2} managed by EasyService{3}</summary>
    public static string Main_Status_Summary(object? p0, object? p1, object? p2, object? p3) => Fmt("Main_Status_Summary", p0, p1, p2, p3);

    /// <summary>{0} - done.</summary>
    public static string Main_Task_Done(object? p0) => Fmt("Main_Task_Done", p0);

    /// <summary>{0} - failed.</summary>
    public static string Main_Task_Failed(object? p0) => Fmt("Main_Task_Failed", p0);

    /// <summary>Creating service "{0}"</summary>
    public static string Main_Task_Install(object? p0) => Fmt("Main_Task_Install", p0);

    /// <summary>Removing service "{0}"</summary>
    public static string Main_Task_Remove(object? p0) => Fmt("Main_Task_Remove", p0);

    /// <summary>Restarting service "{0}"</summary>
    public static string Main_Task_Restart(object? p0) => Fmt("Main_Task_Restart", p0);

    /// <summary>{0}...</summary>
    public static string Main_Task_Running(object? p0) => Fmt("Main_Task_Running", p0);

    /// <summary>Starting service "{0}"</summary>
    public static string Main_Task_Start(object? p0) => Fmt("Main_Task_Start", p0);

    /// <summary>Stopping service "{0}"</summary>
    public static string Main_Task_Stop(object? p0) => Fmt("Main_Task_Stop", p0);

    /// <summary>Updating service "{0}"</summary>
    public static string Main_Task_Update(object? p0) => Fmt("Main_Task_Update", p0);

    /// <summary>Quick setup: pick a program, the rest is pre-filled (or drop an .exe on the window)</summary>
    public static string Main_Tip_Add => Get("Main_Tip_Add");

    /// <summary>Show state and the last log lines of the selected service below the list</summary>
    public static string Main_Tip_Details => Get("Main_Tip_Details");

    /// <summary>Create a new service from this one - same settings, new name</summary>
    public static string Main_Tip_Duplicate => Get("Main_Tip_Duplicate");

    /// <summary>Change the configuration of the selected service</summary>
    public static string Main_Tip_Edit => Get("Main_Tip_Edit");

    /// <summary>Past CPU load, memory and restarts of the selected service</summary>
    public static string Main_Tip_History => Get("Main_Tip_History");

    /// <summary>Live view of the stdout/stderr logs</summary>
    public static string Main_Tip_Logs => Get("Main_Tip_Logs");

    /// <summary>Show only services created with EasyService</summary>
    public static string Main_Tip_OnlyManaged => Get("Main_Tip_OnlyManaged");

    /// <summary>Read the list again (F5)</summary>
    public static string Main_Tip_Refresh => Get("Main_Tip_Refresh");

    /// <summary>Stop and delete the service</summary>
    public static string Main_Tip_Remove => Get("Main_Tip_Remove");

    /// <summary>EasyService - manage Windows services</summary>
    public static string Main_Title => Get("Main_Title");

    /// <summary>CPU {0} %</summary>
    public static string Mon_Cpu(object? p0) => Fmt("Mon_Cpu", p0);

    /// <summary>CPU {0} % (critical from {1} %)</summary>
    public static string Mon_CpuCrit(object? p0, object? p1) => Fmt("Mon_CpuCrit", p0, p1);

    /// <summary>CPU {0} % (warning from {1} %)</summary>
    public static string Mon_CpuWarn(object? p0, object? p1) => Fmt("Mon_CpuWarn", p0, p1);

    /// <summary>The service is disabled.</summary>
    public static string Mon_Disabled => Get("Mon_Disabled");

    /// <summary>The application could not be started: {0}</summary>
    public static string Mon_Failed(object? p0) => Fmt("Mon_Failed", p0);

    /// <summary>health check ok</summary>
    public static string Mon_Healthy => Get("Mon_Healthy");

    /// <summary>The application exited (exit code {0}) and is not restarted per its configuration. The service is running without an application.</summary>
    public static string Mon_Ignored(object? p0) => Fmt("Mon_Ignored", p0);

    /// <summary>RAM {0} MB (critical from {1} MB)</summary>
    public static string Mon_MemCrit(object? p0, object? p1) => Fmt("Mon_MemCrit", p0, p1);

    /// <summary>RAM {0} MB (warning from {1} MB)</summary>
    public static string Mon_MemWarn(object? p0, object? p1) => Fmt("Mon_MemWarn", p0, p1);

    /// <summary>No EasyService configuration is stored for this service.</summary>
    public static string Mon_NoConfig => Get("Mon_NoConfig");

    /// <summary>The service does not exist (any more).</summary>
    public static string Mon_NoService => Get("Mon_NoService");

    /// <summary>The service is running but has not reported any state yet. Is it running an older version of EasyService?</summary>
    public static string Mon_NoState => Get("Mon_NoState");

    /// <summary>PID {0}</summary>
    public static string Mon_Pid(object? p0) => Fmt("Mon_Pid", p0);

    /// <summary>{0} processes</summary>
    public static string Mon_Processes(object? p0) => Fmt("Mon_Processes", p0);

    /// <summary>RAM {0}</summary>
    public static string Mon_Ram(object? p0) => Fmt("Mon_Ram", p0);

    /// <summary>The application is restarting.</summary>
    public static string Mon_Restarting => Get("Mon_Restarting");

    /// <summary>{0} restarts in the last hour (critical from {1})</summary>
    public static string Mon_RestartsCrit(object? p0, object? p1) => Fmt("Mon_RestartsCrit", p0, p1);

    /// <summary>{0} restarts/h</summary>
    public static string Mon_RestartsPerHour(object? p0) => Fmt("Mon_RestartsPerHour", p0);

    /// <summary>{0} restarts total</summary>
    public static string Mon_RestartsTotal(object? p0) => Fmt("Mon_RestartsTotal", p0);

    /// <summary>{0} restarts in the last hour (warning from {1})</summary>
    public static string Mon_RestartsWarn(object? p0, object? p1) => Fmt("Mon_RestartsWarn", p0, p1);

    /// <summary>The service is running but the application is not active.</summary>
    public static string Mon_RunningNoApp => Get("Mon_RunningNoApp");

    /// <summary>Running</summary>
    public static string Mon_RunningPlain => Get("Mon_RunningPlain");

    /// <summary>Running for {0}</summary>
    public static string Mon_RunningSince(object? p0) => Fmt("Mon_RunningSince", p0);

    /// <summary>The last status report is {0} old - the supervising process may have stopped responding.</summary>
    public static string Mon_Stale(object? p0) => Fmt("Mon_Stale", p0);

    /// <summary>The service is starting.</summary>
    public static string Mon_Starting => Get("Mon_Starting");

    /// <summary>CRITICAL</summary>
    public static string Mon_Status_Critical => Get("Mon_Status_Critical");

    /// <summary>OK</summary>
    public static string Mon_Status_Ok => Get("Mon_Status_Ok");

    /// <summary>UNKNOWN</summary>
    public static string Mon_Status_Unknown => Get("Mon_Status_Unknown");

    /// <summary>WARNING</summary>
    public static string Mon_Status_Warning => Get("Mon_Status_Warning");

    /// <summary>The service is {0} although its startup type is "{1}".</summary>
    public static string Mon_StoppedButAuto(object? p0, object? p1) => Fmt("Mon_StoppedButAuto", p0, p1);

    /// <summary>The service is stopped (startup type {0}).</summary>
    public static string Mon_StoppedOk(object? p0) => Fmt("Mon_StoppedOk", p0);

    /// <summary>The application keeps restarting and is being throttled. {0} restarts in the last hour, last exit code {1}.</summary>
    public static string Mon_Throttled(object? p0, object? p1) => Fmt("Mon_Throttled", p0, p1);

    /// <summary>health check failing ({0})</summary>
    public static string Mon_Unhealthy(object? p0) => Fmt("Mon_Unhealthy", p0);

    /// <summary>unknown error</summary>
    public static string Mon_UnknownError => Get("Mon_UnknownError");

    /// <summary>Nothing logged yet: {0}</summary>
    public static string Prev_NoLog(object? p0) => Fmt("Prev_NoLog", p0);

    /// <summary>Select a service to see its state and its last log lines here.</summary>
    public static string Prev_NoSelection => Get("Prev_NoSelection");

    /// <summary>Advanced settings...</summary>
    public static string Quick_Btn_Advanced => Get("Quick_Btn_Advanced");

    /// <summary>Create service</summary>
    public static string Quick_Btn_Create => Get("Quick_Btn_Create");

    /// <summary>Remember credentials for further services</summary>
    public static string Quick_Chk_Remember => Get("Quick_Chk_Remember");

    /// <summary>Start the service immediately</summary>
    public static string Quick_Chk_StartNow => Get("Quick_Chk_StartNow");

    /// <summary>Please correct the following:</summary>
    public static string Quick_Err_Intro => Get("Quick_Err_Intro");

    /// <summary>Check your input</summary>
    public static string Quick_Err_Title => Get("Quick_Err_Title");

    /// <summary>Set up automatically</summary>
    public static string Quick_Group_Auto => Get("Quick_Group_Auto");

    /// <summary>Log on and start</summary>
    public static string Quick_Group_Logon => Get("Quick_Group_Logon");

    /// <summary>Pick a program or drag it here - everything else is pre-filled sensibly.</summary>
    public static string Quick_Hint_Drop => Get("Quick_Hint_Drop");

    /// <summary>Remembered only for your Windows account on this machine (encrypted with DPAPI). Without the check mark the password stays in memory only until EasyService i...</summary>
    public static string Quick_Hint_Remember => Get("Quick_Hint_Remember");

    /// <summary>Account:</summary>
    public static string Quick_Lbl_Account => Get("Quick_Lbl_Account");

    /// <summary>Arguments:</summary>
    public static string Quick_Lbl_Arguments => Get("Quick_Lbl_Arguments");

    /// <summary>Log on as:</summary>
    public static string Quick_Lbl_LogonAs => Get("Quick_Lbl_LogonAs");

    /// <summary>Password:</summary>
    public static string Quick_Lbl_Password => Get("Quick_Lbl_Password");

    /// <summary>Program:</summary>
    public static string Quick_Lbl_Program => Get("Quick_Lbl_Program");

    /// <summary>Service name:</summary>
    public static string Quick_Lbl_ServiceName => Get("Quick_Lbl_ServiceName");

    /// <summary>Startup type:</summary>
    public static string Quick_Lbl_Startup => Get("Quick_Lbl_Startup");

    /// <summary>Local system account (recommended)</summary>
    public static string Quick_Logon_LocalSystem => Get("Quick_Logon_LocalSystem");

    /// <summary>Logs: {0}</summary>
    public static string Quick_Sum_Logs(object? p0) => Fmt("Quick_Sum_Logs", p0);

    /// <summary>Monitoring: on - warning from 3, critical from 10 restarts per hour;</summary>
    public static string Quick_Sum_Monitoring => Get("Quick_Sum_Monitoring");

    /// <summary>available via checkmk, prometheus, check and json.</summary>
    public static string Quick_Sum_MonitoringHow => Get("Quick_Sum_MonitoringHow");

    /// <summary>Restart: after a crash, 1 s delay, throttled on repeated crashes.</summary>
    public static string Quick_Sum_Restart => Get("Quick_Sum_Restart");

    /// <summary>Rotating at 10 MB, the last 10 files are kept.</summary>
    public static string Quick_Sum_Rotation => Get("Quick_Sum_Rotation");

    /// <summary>Set up a service quickly</summary>
    public static string Quick_Title => Get("Quick_Title");

    /// <summary>Start failed</summary>
    public static string State_Failed => Get("State_Failed");

    /// <summary>Application exited (no restart)</summary>
    public static string State_Ignored => Get("State_Ignored");

    /// <summary>Restarting</summary>
    public static string State_Restarting => Get("State_Restarting");

    /// <summary>Running</summary>
    public static string State_Running => Get("State_Running");

    /// <summary>Starting</summary>
    public static string State_Starting => Get("State_Starting");

    /// <summary>Stopped</summary>
    public static string State_Stopped => Get("State_Stopped");

    /// <summary>Restart throttled</summary>
    public static string State_Throttled => Get("State_Throttled");

    /// <summary>Ignore</summary>
    public static string Sup_Action_Ignore => Get("Sup_Action_Ignore");

    /// <summary>Restart</summary>
    public static string Sup_Action_Restart => Get("Sup_Action_Restart");

    /// <summary>Stop service</summary>
    public static string Sup_Action_Stop => Get("Sup_Action_Stop");

    /// <summary>Application exited with code {0} after {1}s. Action: {2}.</summary>
    public static string Sup_AppExited(object? p0, object? p1, object? p2) => Fmt("Sup_AppExited", p0, p1, p2);

    /// <summary>Application exited (code {0}), the service is stopping.</summary>
    public static string Sup_AppExitedStopping(object? p0) => Fmt("Sup_AppExitedStopping", p0);

    /// <summary>The program was not found: {0}</summary>
    public static string Sup_AppNotFound(object? p0) => Fmt("Sup_AppNotFound", p0);

    /// <summary>Application started (PID {0}).</summary>
    public static string Sup_AppStarted(object? p0) => Fmt("Sup_AppStarted", p0);

    /// <summary>The EasyService diagnostic log could not be opened: {0}</summary>
    public static string Sup_EventLogOpenFailed(object? p0) => Fmt("Sup_EventLogOpenFailed", p0);

    /// <summary>Health check failed {0} times in a row: {1}</summary>
    public static string Sup_HealthFailed(object? p0, object? p1) => Fmt("Sup_HealthFailed", p0, p1);

    /// <summary>Health check failed ({0} of {1}): {2}</summary>
    public static string Sup_HealthFailedOnce(object? p0, object? p1, object? p2) => Fmt("Sup_HealthFailedOnce", p0, p1, p2);

    /// <summary>Health check is fine again: {0}</summary>
    public static string Sup_HealthRecovered(object? p0) => Fmt("Sup_HealthRecovered", p0);

    /// <summary>Restarting the application because the health check keeps failing: {0}</summary>
    public static string Sup_HealthRestart(object? p0) => Fmt("Sup_HealthRestart", p0);

    /// <summary>The application did not respond; terminating the process.</summary>
    public static string Sup_KillProcess => Get("Sup_KillProcess");

    /// <summary>The application did not respond; terminating the process tree.</summary>
    public static string Sup_KillTree => Get("Sup_KillTree");

    /// <summary>The {0} log file could not be opened ({1}): {2}</summary>
    public static string Sup_LogOpenFailed(object? p0, object? p1, object? p2) => Fmt("Sup_LogOpenFailed", p0, p1, p2);

    /// <summary>Next start attempt in {0} ms.</summary>
    public static string Sup_NextAttempt(object? p0) => Fmt("Sup_NextAttempt", p0);

    /// <summary>Note: the process could not be assigned to a job object; child processes may survive shutdown and resource measurement covers the main process only.</summary>
    public static string Sup_NoJobObject => Get("Sup_NoJobObject");

    /// <summary>The application will not be restarted; the service stays up.</summary>
    public static string Sup_NoRestart => Get("Sup_NoRestart");

    /// <summary>The application is not responding and must not be terminated according to its configuration.</summary>
    public static string Sup_NoTerminate => Get("Sup_NoTerminate");

    /// <summary>{0} failed: {1}</summary>
    public static string Sup_OpFailed(object? p0, object? p1) => Fmt("Sup_OpFailed", p0, p1);

    /// <summary>Starting {0}</summary>
    public static string Sup_Op_Start(object? p0) => Fmt("Sup_Op_Start", p0);

    /// <summary>stderr pipe</summary>
    public static string Sup_Op_StderrPipe => Get("Sup_Op_StderrPipe");

    /// <summary>stdin pipe</summary>
    public static string Sup_Op_StdinPipe => Get("Sup_Op_StdinPipe");

    /// <summary>stdout pipe</summary>
    public static string Sup_Op_StdoutPipe => Get("Sup_Op_StdoutPipe");

    /// <summary>The {0} reader stopped: {1}</summary>
    public static string Sup_ReaderStopped(object? p0, object? p1) => Fmt("Sup_ReaderStopped", p0, p1);

    /// <summary>Resources could not be measured: {0}</summary>
    public static string Sup_SampleFailed(object? p0) => Fmt("Sup_SampleFailed", p0);

    /// <summary>Sent Ctrl+C to the application.</summary>
    public static string Sup_SentCtrlC => Get("Sup_SentCtrlC");

    /// <summary>Sent WM_CLOSE to the application's windows.</summary>
    public static string Sup_SentWmClose => Get("Sup_SentWmClose");

    /// <summary>Sent WM_QUIT to the application's threads.</summary>
    public static string Sup_SentWmQuit => Get("Sup_SentWmQuit");

    /// <summary>The service is stopping.</summary>
    public static string Sup_ServiceStopping => Get("Sup_ServiceStopping");

    /// <summary>The application could not be started: {0}</summary>
    public static string Sup_StartFailed(object? p0) => Fmt("Sup_StartFailed", p0);

    /// <summary>The service is stopping as configured by its exit action (exit code {0}).</summary>
    public static string Sup_StoppedByPolicy(object? p0) => Fmt("Sup_StoppedByPolicy", p0);

    /// <summary>EasyService is now supervising "{0}".</summary>
    public static string Sup_Supervising(object? p0) => Fmt("Sup_Supervising", p0);

    /// <summary>The application ran for less than the throttle window ({0} ms); next attempt in {1} ms. Restarts in the last hour: {2}.</summary>
    public static string Sup_Throttled(object? p0, object? p1, object? p2) => Fmt("Sup_Throttled", p0, p1, p2);

    /// <summary>Another EasyService process has been changing services for more than {0} seconds. Try again once it is done.</summary>
    public static string Svc_Err_Busy(object? p0) => Fmt("Svc_Err_Busy", p0);

    /// <summary>The service configuration could not be changed</summary>
    public static string Svc_Err_ChangeConfig => Get("Svc_Err_ChangeConfig");

    /// <summary>The service could not be resumed</summary>
    public static string Svc_Err_Continue => Get("Svc_Err_Continue");

    /// <summary>The service could not be created: {0}</summary>
    public static string Svc_Err_Create(object? p0) => Fmt("Svc_Err_Create", p0);

    /// <summary>The service could not be removed: {0}</summary>
    public static string Svc_Err_Delete(object? p0) => Fmt("Svc_Err_Delete", p0);

    /// <summary>The service stopped again immediately (error code {0}). Details are in the service's EasyService log.</summary>
    public static string Svc_Err_DiedOnStart(object? p0) => Fmt("Svc_Err_DiedOnStart", p0);

    /// <summary>The services could not be listed</summary>
    public static string Svc_Err_Enumerate => Get("Svc_Err_Enumerate");

    /// <summary>A service named "{0}" already exists.</summary>
    public static string Svc_Err_Exists(object? p0) => Fmt("Svc_Err_Exists", p0);

    /// <summary>Service "{0}" is marked for deletion. Please reboot and try again.</summary>
    public static string Svc_Err_MarkedForDelete(object? p0) => Fmt("Svc_Err_MarkedForDelete", p0);

    /// <summary>The service control manager could not be opened</summary>
    public static string Svc_Err_OpenScm => Get("Svc_Err_OpenScm");

    /// <summary>Service "{0}" could not be opened</summary>
    public static string Svc_Err_OpenService(object? p0) => Fmt("Svc_Err_OpenService", p0);

    /// <summary>The service could not be paused</summary>
    public static string Svc_Err_Pause => Get("Svc_Err_Pause");

    /// <summary>The service status could not be queried</summary>
    public static string Svc_Err_QueryStatus => Get("Svc_Err_QueryStatus");

    /// <summary>The registry key for {0} could not be opened.</summary>
    public static string Svc_Err_RegistryOpen(object? p0) => Fmt("Svc_Err_RegistryOpen", p0);

    /// <summary>The service could not be started: {0}</summary>
    public static string Svc_Err_Start(object? p0) => Fmt("Svc_Err_Start", p0);

    /// <summary>The service could not be stopped: {0}</summary>
    public static string Svc_Err_Stop(object? p0) => Fmt("Svc_Err_Stop", p0);

    /// <summary>Timed out waiting for the service to reach its target state.</summary>
    public static string Svc_Err_Timeout => Get("Svc_Err_Timeout");

    /// <summary>Automatic</summary>
    public static string Svc_Startup_Automatic => Get("Svc_Startup_Automatic");

    /// <summary>Automatic (delayed)</summary>
    public static string Svc_Startup_AutomaticDelayed => Get("Svc_Startup_AutomaticDelayed");

    /// <summary>Disabled</summary>
    public static string Svc_Startup_Disabled => Get("Svc_Startup_Disabled");

    /// <summary>Manual</summary>
    public static string Svc_Startup_Manual => Get("Svc_Startup_Manual");

    /// <summary>Resuming...</summary>
    public static string Svc_State_ContinuePending => Get("Svc_State_ContinuePending");

    /// <summary>Pausing...</summary>
    public static string Svc_State_PausePending => Get("Svc_State_PausePending");

    /// <summary>Paused</summary>
    public static string Svc_State_Paused => Get("Svc_State_Paused");

    /// <summary>Running</summary>
    public static string Svc_State_Running => Get("Svc_State_Running");

    /// <summary>Starting...</summary>
    public static string Svc_State_StartPending => Get("Svc_State_StartPending");

    /// <summary>Stopping...</summary>
    public static string Svc_State_StopPending => Get("Svc_State_StopPending");

    /// <summary>Stopped</summary>
    public static string Svc_State_Stopped => Get("Svc_State_Stopped");

    /// <summary>Unknown</summary>
    public static string Svc_State_Unknown => Get("Svc_State_Unknown");
}
